### ISSUE TITLE
playAgainPrompt() method will not take input (Scanner issue?)

### ISSUE THREAD

**Issue by SirXOPHER** [SirXOPHER/Hangman#3]
A basic implementation of the game has been built, but the user prompt to ask for a replay has an issue. The method `playAgainPrompt()` is implemented and has been tested individually. However, when called in context it will not take user input. The program is being terminated instead. If the first round of the game is omitted (i.e. first occurence of `playRound();` put inside a comment), the user prompt will work as intended, but will fail after the next round, if a replay has been chosen.

**Comment by albertopoljak** [comment]
scan.close() closes System.in stream,  so the next time you initialize scanner with "System.in" it will fail to open that stream. Once closed there is no easy way to re-open it again. But this is a easy fix - only use ONE scanner for user input  (you used 2) and close it only when the game has ended (user selects NO.)

**Comment by SirXOPHER** [comment]
Brilliant! Thank you for your resolution and explanation. I suspected it would have to do with how I was reading user input from a scanner, but couldn't locate the problem. I guess I somehow thought it would be good practice to dedicate a separate scanner everytime one is required. But as it seems, the complete opposite is a much better idea. It makes absolute sense to have one scanner reading all user input throughout the game and only close it when the game finishes. The scanners reading the textfiles do not seem to struggle with being closed and reopened. Well, at least the one `game_state` providing the visual outputs is being initialized and closed at every round of the game.
